# Generated by Django 4.0.4 on 2022-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
